apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ci-cd-pipeline
spec:
  workspaces:
    - name: output
  params:
    - name: app-name
      type: string
      description: The name of the application
    - name: build-image
      type: string
      description: The image to build
  tasks:
    - name: cleanup
      taskRef:
        name: cleanup
      workspaces:
        - name: source
          workspace: output

    - name: git-clone
      taskRef:
        name: git-clone
      runAfter:
        - cleanup
      params:
        - name: url
          value: "https://github.com/hamezachr/ci-cd-final-project.git"
        - name: revision
          value: "main"
      workspaces:
        - name: output
          workspace: output

    - name: flake8-linting
      taskRef:
        name: flake8
      runAfter:
        - git-clone
      workspaces:
        - name: source
          workspace: output

    - name: nose-tests
      taskRef:
        name: nose
      runAfter:
        - git-clone
      params:
        - name: args
          value: "-v"
      workspaces:
        - name: output  # Changed from 'source' to 'output'
          workspace: output

    - name: buildah
      taskRef:
        name: buildah
      runAfter:
        - nose-tests  # Ensure buildah runs after nose-tests
      workspaces:
        - name: source
          workspace: output
      params:
        - name: IMAGE
          value: "$(params.build-image)"

    - name: deploy
      taskRef:
        name: openshift-client
      runAfter:
        - buildah  # Ensure deploy runs after buildah
      params:
        - name: SCRIPT
          value: |
            oc create deployment $(params.app-name) --image=$(params.build-image) --dry-run=client -o yaml | oc apply -f -
